name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          scope: '@foo-software'
      - name: Install
        run: |
          npm install --workspaces
          npm run build --workspaces --if-present
      - name: Generate Schema
        run: |
          node packages/ghost-graphql-ci-tools/dist/bin/config-git.js
          node packages/ghost-graphql/dist/bin/generate-schema.js
          node packages/ghost-graphql-ci-tools/dist/bin/commit-schema.js
      - name: Publish Packages
        run: |
          node packages/ghost-graphql-ci-tools/dist/bin/publish-packages.js
