name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          scope: '@foo-software'
      - name: Install
        run: |
          npm install --workspaces
          npm run build --workspaces --if-present
      - name: Integration Tests
        run: |
          cd packages/ghost-graphql-integration-tests
          npm run test
